### ISSUE TITLE
Dependency error while building AACT with Maven

### ISSUE THREAD

**Issue by L3thal14** [LightningRS/AACT#1]
I am trying to build AACT but encountered this error shown below because one of the dependencies is missing. Removing it from the `pom.xml` file resulted in more error logs:
```
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< com.iscas:aact >---------------------------
[INFO] Building aact 0.1.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for acts:acts:jar:3.2.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.878 s
[INFO] Finished at: 2023-02-17T14:19:09-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aact: Could not resolve dependencies for project com.iscas:aact:jar:0.1.1-SNAPSHOT: acts:acts:jar:3.2.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```
I could not find an alternative to this package. It would be helpful if you could fix this.

**Comment by LightningRS** [comment]
Hi @L3thal14, apologize for the late response.

The library "ACTS" used in AACT is provided by NIST (National Institute of Standards and Technology), which is not yet publicly available. For more information, please visit [this page](https://csrc.nist.rip/groups/SNS/acts/download_tools.html#acts).

In order to maintain the integrity of the maven build process, we added the jar file of the library to the project and tested it on the GitHub CI build: https://github.com/LightningRS/AACT/commit/2bbc5f5b1ffc6987fde59700a7aede59aac4a356

We hope this has solved your issue. If you still have questions, please continue to contact me.
